apiVersion: v1
data:
  altGreeting: Welcome to dev!
  enableRisky: "true"
kind: ConfigMap
metadata:
  annotations:
    note: Hello, I am dev!
  labels:
    app: hello
    variant: dev
  name: dev-the-map-universe
