apiVersion: v1
kind: Service
metadata:
  annotations:
    note: Hello, I am dev!
  labels:
    app: hello
    variant: dev
  name: dev-the-service
spec:
  ports:
  - port: 8666
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello
    deployment: hello
    variant: dev
  type: LoadBalancer
