name: Kargo Render PR Generator

on:
  pull_request:
    branches:
    - master

permissions:
  contents: write
  pull-requests: write # Optional, depending on your workflow

jobs:
  render-manifests:
    name: Render and Commit Manifests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetBranch:
        - dev
        - stg-secondary
        - stg
    steps:
    - name: Output GITHUB_SHA
      run: |
        echo "GITHUB_SHA=${GITHUB_SHA}"
        echo "GITHUB_REF=${GITHUB_REF}"
        echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
        echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
        echo "GITHUB_REF_PROTECTED=${GITHUB_REF_PROTECTED}"
        echo "GITHUB_REF_TYPE=${GITHUB_REF_TYPE}"
        echo "GITHUB_WORKFLOW_SHA=${GITHUB_WORKFLOW_SHA}"

        echo "github.event.pull_request.head.sha=${github.event.pull_request.head.sha}"
        echo "github.sha=${github.sha}"
        echo "from GITHUB_EVENT_PATH: $(cat $GITHUB_EVENT_PATH | jq -r .pull_request.head.sha)"

    - name: Render and Commit Manifests
      uses: akuity/kargo-render-action@v0.1.0-rc.40
      with:
        personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
        targetBranch: helloUniverse/${{ matrix.targetBranch }}
